"""
inspect_encounter_surrogate_data_v1.py

Inspect encounter-level surrogate data generated by
    generate_encounter_surrogate_data_v1.py
or merged by
    merge_encounter_surrogate_shards_v1.py

Example:
    python -B inspect_encounter_surrogate_data_v1.py --file encounter_surrogate_v1_merged.npz --out-dir surrogate_inspect
"""

import argparse
import os
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

EPS = 3e-4
Z3_R_MIN = 0.052
Z3_R_MAX = 0.148
ADAPT_THRESH = 0.05
NN_THRESH = 0.15

REQUIRED_FIELDS = [
    "m", "x0", "v0", "x_ias_final", "v_ias_final", "x_nonn_final", "v_nonn_final",
    "residual_x", "residual_v", "X_raw21", "X_rel18", "dt", "window_years",
    "active_i", "active_j", "third_k", "r_pair", "r_soft_pair", "v_rad_norm", "v_tan_norm",
    "source_row_idx", "category_id", "E0", "E_ias_final", "E_nonn_final", "relE_ias",
    "relE_nonn", "Lz0", "min_r_ias", "min_r_nonn", "max_radius_ias", "max_radius_nonn",
    "nonn_steps", "nonn_substeps", "nonn_zone1", "nonn_zone2", "nonn_zone3", "nonn_zone4",
    "pos_residual_rms", "vel_residual_rms", "nonn_pos_error_rms",
]

plt.rcParams.update({
    "font.family": "serif", "font.size": 11, "axes.titlesize": 12,
    "axes.labelsize": 11, "figure.dpi": 150, "savefig.dpi": 200,
    "savefig.bbox": "tight",
})


def parse_args():
    ap = argparse.ArgumentParser(description="Inspect encounter surrogate v1 data.")
    ap.add_argument("--file", default="encounter_surrogate_v1_merged.npz")
    ap.add_argument("--out-dir", "--out_dir", dest="out_dir", default="surrogate_inspect")
    return ap.parse_args()


def line_range(name, x):
    x = np.asarray(x, dtype=np.float64)
    print(f"{name:20s} min={np.min(x): .6e} med={np.median(x): .6e} max={np.max(x): .6e}")


def main():
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)
    try:
        data = np.load(args.file)
    except FileNotFoundError:
        print(f"ERROR: {args.file} not found")
        sys.exit(1)

    missing = [k for k in REQUIRED_FIELDS if k not in data.files]
    print("=" * 88)
    print(f"INSPECT REPORT -- {args.file}")
    print("=" * 88)
    print("FIELDS:")
    print(list(data.files))
    print("\nMISSING:")
    print(missing)
    if missing:
        raise KeyError(f"Missing required fields: {missing}")

    n = len(data["r_pair"])
    print("\nSHAPES:")
    for k in REQUIRED_FIELDS:
        arr = data[k]
        print(f"{k:20s} {arr.shape} {arr.dtype}")
        if len(arr) != n:
            raise ValueError(f"Field {k} length {len(arr)} != {n}")

    finite_all = all(np.all(np.isfinite(data[k])) for k in REQUIRED_FIELDS)
    r = data["r_pair"].astype(np.float64)
    rsoft = data["r_soft_pair"].astype(np.float64)
    vr = data["v_rad_norm"].astype(np.float64)
    vt = data["v_tan_norm"].astype(np.float64)
    relE_ias = data["relE_ias"].astype(np.float64)
    relE_nonn = data["relE_nonn"].astype(np.float64)
    min_ias = data["min_r_ias"].astype(np.float64)
    min_nonn = data["min_r_nonn"].astype(np.float64)
    posR = data["pos_residual_rms"].astype(np.float64)
    velR = data["vel_residual_rms"].astype(np.float64)
    cat = data["category_id"].astype(np.int32)
    dt = np.array([round(float(x), 4) for x in data["dt"]])

    print("\nRANGES:")
    for name, arr in [
        ("r_pair", r), ("r_soft_pair", rsoft), ("v_rad_norm", vr), ("v_tan_norm", vt),
        ("relE_ias", relE_ias), ("relE_nonn", relE_nonn),
        ("min_r_ias", min_ias), ("min_r_nonn", min_nonn),
        ("pos_residual_rms", posR), ("vel_residual_rms", velR),
        ("max_radius_ias", data["max_radius_ias"]), ("max_radius_nonn", data["max_radius_nonn"]),
    ]:
        line_range(name, arr)

    print("\nCHECKS:")
    checks = {
        "finite all": finite_all,
        "r_pair in Zone 3": bool(np.all((r > Z3_R_MIN) & (r < Z3_R_MAX))),
        "r_soft matches sqrt(r^2+eps^2)": bool(np.allclose(rsoft, np.sqrt(r*r + EPS*EPS), rtol=2e-5, atol=2e-7)),
        "v_tan_norm nonnegative": bool(np.all(vt >= 0)),
        "IAS15 min_r >= Zone2 boundary": bool(np.all(min_ias >= ADAPT_THRESH - 1e-10)),
        "residual_x exactly IAS15 - noNN": bool(np.allclose(data["residual_x"], data["x_ias_final"] - data["x_nonn_final"], rtol=2e-8, atol=2e-10)),
        "residual_v exactly IAS15 - noNN": bool(np.allclose(data["residual_v"], data["v_ias_final"] - data["v_nonn_final"], rtol=2e-8, atol=2e-10)),
        "X_raw21 shape": bool(data["X_raw21"].shape == (n, 21)),
        "X_rel18 shape": bool(data["X_rel18"].shape == (n, 18)),
    }
    for k, v in checks.items():
        print(f"{k}: {v}")

    print("\nVELOCITY BALANCE:")
    print(f"  approaching vr<0          : {int(np.sum(vr < 0)):6d} ({np.mean(vr < 0):6.1%})")
    print(f"  strong approach vr<-0.6   : {int(np.sum(vr < -0.6)):6d} ({np.mean(vr < -0.6):6.1%})")
    print(f"  weak/side -0.6<=vr<=0.2   : {int(np.sum((vr >= -0.6) & (vr <= 0.2))):6d} ({np.mean((vr >= -0.6) & (vr <= 0.2)):6.1%})")
    print(f"  receding vr>0.2           : {int(np.sum(vr > 0.2)):6d} ({np.mean(vr > 0.2):6.1%})")
    print(f"  category strong/weak/rec/broad: {int(np.sum(cat==0))}/{int(np.sum(cat==1))}/{int(np.sum(cat==2))}/{int(np.sum(cat==3))}")

    print("\nSUMMARY BY dt:")
    print(f"  {'dt':>7} | {'n':>6} | {'vr_med':>8} | {'vt_med':>8} | {'strong':>7} | {'rec':>7} | {'posR_med':>10} | {'relE_nonn_p95':>13}")
    print("  " + "-" * 91)
    for d in sorted(set(dt)):
        mask = dt == d
        print(
            f"  {d:7.4f} | {int(mask.sum()):6d} | {np.median(vr[mask]):+8.3f} | {np.median(vt[mask]):8.3f} | "
            f"{np.mean(vr[mask] < -0.6):7.1%} | {np.mean(vr[mask] > 0.2):7.1%} | "
            f"{np.median(posR[mask]):10.3e} | {np.percentile(relE_nonn[mask],95):13.3e}"
        )

    print("\nRED FLAGS:")
    red = []
    if not finite_all: red.append("non-finite values")
    if not checks["r_pair in Zone 3"]: red.append("some starting pairs outside Zone 3")
    if np.mean(vr < -0.6) < 0.20: red.append("thin strong-approach coverage")
    if np.mean(vr > 0.2) < 0.15: red.append("thin receding coverage")
    if np.percentile(relE_nonn, 95) > 5e-2: red.append("noNN energy p95 exceeds 5%")
    if np.max(posR) > 5.0: red.append("large residual outlier > 5 AU")
    if np.min(min_ias) < ADAPT_THRESH - 1e-10: red.append("IAS15 window enters Zone 2 despite prototype filter")
    if red:
        for item in red:
            print(f"  WARNING: {item}")
        verdict = "PROCEED WITH CAUTION"
    else:
        print("  None")
        verdict = "PROCEED: clean prototype data"

    # Figures.
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.scatter(vr, posR, s=10, alpha=0.6)
    ax.axvline(0, lw=1, ls="--")
    ax.set_xlabel("v_rad_norm")
    ax.set_ylabel("Position residual RMS (AU)")
    ax.set_title("Encounter residual size vs radial velocity")
    fig.savefig(os.path.join(args.out_dir, "fig1_residual_vs_vrad.png"))
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(posR, bins=40)
    ax.set_xlabel("Position residual RMS (AU)")
    ax.set_ylabel("count")
    ax.set_title("Residual target distribution")
    fig.savefig(os.path.join(args.out_dir, "fig2_residual_hist.png"))
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.scatter(min_ias, relE_nonn, s=10, alpha=0.6)
    ax.axvline(ADAPT_THRESH, lw=1, ls="--")
    ax.set_xlabel("IAS15 min pair distance in window (AU)")
    ax.set_ylabel("noNN relative energy drift")
    ax.set_yscale("log")
    ax.set_title("Energy drift vs closest approach")
    fig.savefig(os.path.join(args.out_dir, "fig3_energy_vs_minr.png"))
    plt.close(fig)

    print("\nSaved figures:")
    for f in ["fig1_residual_vs_vrad.png", "fig2_residual_hist.png", "fig3_energy_vs_minr.png"]:
        print(" ", os.path.join(args.out_dir, f))
    print("\n" + "=" * 88)
    print("FINAL VERDICT:", verdict)
    print("=" * 88)


if __name__ == "__main__":
    main()
